# Familiarizandose con **Numpy**

Referencias:

- https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python
- https://towardsdatascience.com/a-cheat-sheet-on-generating-random-numbers-in-numpy-5fe95ec2286

## **Ejercicio 1)** Importando librerías

Importe las librerías `numpy` para operar con arrays, `scipy` para operar con algebra lineal y `matplotlib.pyplot` para graficar.


In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

## **Ejercicio 2)** Creando arrays

**1)** Cree un array de enteros `a` a partir de la lista `[1,2,3]`.

**2)** Cree un array bidimensional de flotantes `b` a partir de la lista de listas `[[1.5,2,3],[4,5,6]]`.

**3)** Cree un array tridimensional de flotantes `c` a partir de la lista de listas `[[[1.5,2,3],[4,5,6]],[[3,2,1],[4,5,6]]]`.


In [9]:
# 2.1)
a = np.array([1,2,3])
print(f"{a}\n")

# 2.2)

b = np.array([[1.5,2,3],[4,5,6]])
print(b)

# 2.3)
c = np.array([[[1.5, 2, 3], [4, 5, 6]], [[3, 2, 1], [4, 5, 6]]])
print(c)

[1 2 3]

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


## **Ejercicio 3)** Inicializando arrays

**1)** Utilice `np.zeros` para crear un array bidimensional de flotantes incializados a `0.0`, y de dimensiones de tamaños `(3,4)`.

**2)** Utilice `np.ones` para crear un array tridimensional de enteros inicializados a `1`, y de dimensiones `(2,3,4)`.

**3)** Utilice `np.arange` para crear un array `d` de valores enteros equiespaciados de a `5` entre `10` y `25`.

**4)** Utilice `np.linspace` para crear un array de `9` valores flotantes equiespaciados entre `0.0` y `9.0`.

**5)** Utilice `np.full` para crear un array bidimensional llamado `e` de entradas iguales a `7`, y de dimesiones `(2,2)`.

**6)** Utilice `np.eye` para crear una matriz identidad llamada `f` de dimensiones 2x2.

**7)** Utilice `np.random.random` para crear un array bidimensional de dimensiones 2x2 inicializado con valores aleatorios uniformemente sorteados del intervalo $[0,1]$.

**8)** Utilice `np.empty` para crear un array bidimensional sin inicializar y de dimensiones `(3,2)`.


In [10]:
#  3.1)

arr_zeros = np.zeros((3,4), dtype=np.float64)
print(arr_zeros)

# 3.2)

arr_ones = np.ones((2,3,4), dtype=np.int32)
print(arr_ones)

# 3.3)

d = np.arange(10, 25, 5)
print(d)

# 3.4)

arr_linspace = np.linspace(0.0, 9.0, 9)
print(arr_linspace)

# 3.5)
e = np.full((2,2), 7)
print(e)

# 3.6)
f = np.eye(2)
print(f)

# 3.7)
arr_random = np.random.random((2,2))
print(arr_random)

# 3.8)
arr_empty = np.empty((3,2))
print(arr_empty)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[10 15 20]
[0.    1.125 2.25  3.375 4.5   5.625 6.75  7.875 9.   ]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.04195738 0.99230836]
 [0.53067276 0.07909745]]
[[1.5 2. ]
 [3.  4. ]
 [5.  6. ]]


## **Ejercicio 4)** Inspeccionando arrays

Considere los arrays de los ejercicios 2) y 3).

**1)** Utilizando `.shape`, determine cuales son las dimensiones del array `a`.

**2)** Utilizando la función `len()`, determine el _largo_ del array `a`.

**3)** Utilizando `.ndim`, determine el número de dimensiones del array `b`.

**4)** Utilizando `.size`, determine el número de entradas que tienen `e`.

**5)** Utilizando `.dtype`, determine el tipo de los datos contenidos por el array `b`.

**6)** Utilizando `.dtype.name`, determine el nombre del tipo de los datos contenidos por el array `b`.

**7)** Utilizando `.astype`, convierta el array `b` a un array de tipo `int`.


In [11]:
# 4.1)
print(f"Dimensiones de a: {a.shape}\n")

# 4.2)
print(f"Largo de a: {len(a)}\n")

# 4.3)
print(f"Número de dimensiones de b: {b.ndim}\n")

# 4.4)
print(f"Número de entradas de e: {e.size}\n")

# 4.5)
print(f"Tipo de datos de b: {b.dtype}\n")

# 4.6)
print(f"Nombre de los tipo de datos de b: {b.dtype.name}\n")

# 4.7)
b.astype(int)

Dimensiones de a: (3,)

Largo de a: 3

Número de dimensiones de b: 2

Número de entradas de e: 4

Tipo de datos de b: float64

Nombre de los tipo de datos de b: float64



array([[1, 2, 3],
       [4, 5, 6]])

## **Ejercicio 5)** Tipos de datos

**1)** Cree un array que contenga elementos de tipo `np.int64`.

**2)** Cree un array que contenga elementos de tipo `np.float32`.

**3)** Cree un array que contenga elementos de tipo `np.complex128`.

**4)** Cree un array que contenga elementos de tipo `np.bool`.

**5)** Cree un array que contenga elementos de tipo `np.object`.

**6)** Cree un array que contenga elementos de tipo `np.bytes_`.

**7)** Cree un array que contenga elementos de tipo `np.str_`.


In [12]:
# 5.1)
arr_int64 = np.array([1, 2, 3], dtype=np.int64)

# 5.2)
arr_float32 = np.array([1.0, 2.0, 3.0], dtype=np.float32)

# 5.3)
arr_complex128 = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

# 5.4)
arr_bool = np.array([True, False, True], dtype=np.bool_)

# 5.5)
arr_object = np.array([1, "two", 3.0], dtype=np.object_)

# 5.6)
arr_bytes = np.array([b'hello', b'world'], dtype=np.bytes_)

# 5.7)
arr_str = np.array(['hello', 'world'], dtype=np.str_)



## **Ejercicio 6)** Operando sobre arrays

Considere los arrays de los ejercicios 2) y 3).

**1)** Calcule la resta `a-b` de los arrays `a` y `b` y almacene el resultado en un array `g`.

**2)** Notar que `a` y `b` poseen diferentes dimensiones (i.e., `a.shape` es distinto de `b.shape`) y, sin embargo, en el inciso anterior numpy computa la resta `a-b`. Explique lo que ocurre.

**3)** Compare el anterior resultado con el uso de `np.substract`.

**4)** Calcule la suma `a+b` de los arrays `a` y `b`.

**5)** Compare el anterior resultado con el uso de `np.add`.

**6)** Calcule la división punto a punto `a/b` de `a` y `b`.

**7)** Compare el anterior resultado con el uso de `np.divide`.

**8)** Calcule la multiplicación punto a punto `a*b` de `a` y `b`.

**9)** Compare el anterior resultado con el uso de `np.multiply`.

**10)** Calcule la exponencial punto a punto `np.exp(b)` de `b`.

**11)** Calcule la raíz cuadrada punto a punto `np.sqrt(b)` de `b`.

**12)** Calcule el seno punto a punto `np.sin(a)` de `a`.

**13)** Calcule el coseno punto a punto `np.cos(b)` de `b`.

**14)** Calcule el logaritmo natural punto a punto `np.log(a)` de `a`.

**15)** Calcule el producto punto `e.dot(f)` entre `e` y `f`.

**16)** Compare el anterior resultado con el uso de `np.dot`.

**17)** Explique las diferentes opciones que puede adoptar el producto punto de numpy según el número de dimensiones que tengan sus factores.

**Ayuda:** use https://numpy.org/doc/stable/reference/generated/numpy.dot.html


In [18]:
# 6.1)
print("Inciso 6.1")
g = a - b
print(g)

# 6.2)
# Numpy aplica broadcasting para poder operar arrays de diferentes dimensiones.

# 6.3)
print("Inciso 6.3")
g2 = np.subtract(a, b)
print(g2)
print(g == g2)

# 6.4)
print("Inciso 6.4")
h = a + b
print(h)

# 6.5)
print("Inciso 6.5")
h2 = np.add(a, b)
print(h2)
print(h == h2)

# 6.6)
print("Inciso 6.6")
i = a / b
print(i)

# 6.7)
print("Inciso 6.7")
i2 = np.divide(a, b)
print(i2)
print(i == i2)

# 6.8)
print("Inciso 6.8")
j = a * b
print(j)


Inciso 6.1
[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]
Inciso 6.3
[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]
[[ True  True  True]
 [ True  True  True]]
Inciso 6.4
[[2.5 4.  6. ]
 [5.  7.  9. ]]
Inciso 6.5
[[2.5 4.  6. ]
 [5.  7.  9. ]]
[[ True  True  True]
 [ True  True  True]]
Inciso 6.6
[[0.66666667 1.         1.        ]
 [0.25       0.4        0.5       ]]
Inciso 6.7
[[0.66666667 1.         1.        ]
 [0.25       0.4        0.5       ]]
[[ True  True  True]
 [ True  True  True]]
Inciso 6.8
[[ 1.5  4.   9. ]
 [ 4.  10.  18. ]]


In [19]:
# 6.9)
print("Inciso 6.9")
j2 = np.multiply(a, b)
print(j2)
print(j == j2)

Inciso 6.9
[[ 1.5  4.   9. ]
 [ 4.  10.  18. ]]
[[ True  True  True]
 [ True  True  True]]


In [17]:
# 6.10)
print("Inciso 6.10")
k = np.exp(b)
print(k)

# 6.11)
p = np.sqrt(b)
print(l)

# 6.12)
print("Inciso 6.12")
m = np.sin(a)
print(m)

# 6.13)
print("Inciso 6.13")
n = np.cos(b)
print(n)

# 6.14)
print("Inciso 6.14")
o = np.log(a)
print(o)

# 6.15)
print("Inciso 6.15")
p = e.dot(f)
print(p)

# 6.16)
print("Inciso 6.16")
p2 = np.dot(e, f)
print(p2)
print(p == p2)

# 6.17)
# Si ambos arrays son 1-D, el producto punto es el producto escalar de los
# vectores. Si ambos son 2-D, es la multiplicación matricial. Si uno de los
# argumentos es N-D, N>2, se trata como una matriz de sus últimas dos
# dimensiones y las otras dimensiones se consideran como índices. Si los
# arrays no son al menos 1-D, se lanza un ValueError.
# Si las dimensiones no son compatibles, se lanza un ValueError.
# Si los arrays son de enteros o booleanos, el resultado es un entero. Si
# alguno de los arrays es de punto flotante, el resultado es un punto
# flotante. De manera similar, si alguno de los arrays es complejo, el
# resultado es complejo.  rint("Inciso 6.11")
l  

Inciso 6.10
[[  4.48168907   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[1.22474487 1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
Inciso 6.12
[0.84147098 0.90929743 0.14112001]
Inciso 6.13
[[ 0.0707372  -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
Inciso 6.14
[0.         0.69314718 1.09861229]
Inciso 6.15
[[7. 7.]
 [7. 7.]]
Inciso 6.16
[[7. 7.]
 [7. 7.]]
[[ True  True]
 [ True  True]]


array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

## **Ejercicio 7)** Comparando arrays

**1)** Use `==` para realizar una compación punto a punto de los arrays `a` y `b`.

**2)** Use `<` para realizar una comparación punto a punto del array `b` con el escalar `2`.

**3)** Use `np.array_equal(a,b)` para determinar si `a` y `b` son iguales como arrays.


In [21]:
# 7.1)
print("Inciso 7.1")
print(a == b)

# 7.2)
print("Inciso 7.2")
print(b < 2)

# 7.3)
print("Inciso 7.3")
print(np.array_equal(a,b))

Inciso 7.1
[[False  True  True]
 [False False False]]
Inciso 7.2
[[ True False False]
 [False False False]]
Inciso 7.3
False


## **Ejercicio 8)** _Copiando_ arrays

**1)** Use `.view()` para crear una vista llamada `h` del array `a`.

**2)** Use `.copy()` para crear una copia del array `a`.


In [23]:
# 8.1)
print("Inciso 8.1")
h = a.view()
print(h)

# 8.2)
print("Inciso 8.2")
h2 = a.copy()
print(h2)

#La diferencia entre view y copy es que la vista comparte la misma memoria que el array original, mientras que la copia crea un nuevo array en una ubicación de memoria diferente. Por lo tanto, los cambios realizados en la vista afectarán al array original, mientras que los cambios realizados en la copia no afectarán al array original.


Inciso 8.1
[1 2 3]
Inciso 8.2
[1 2 3]


## **Ejercicio 9)** Ordenado

**1)** Use `.sort()` para ordenar los elementos de `a`.

**2)** Ordene los elementos de `c` a lo largo del eje `0`. Explique.


In [24]:
# 9.1)
print("Inciso 9.1")
a.sort()
print(a)

# 9.2)
print("Inciso 9.2")
c.sort(axis=0)
print(c)

# Explicacion
# Al ordenar a lo largo del eje 0, se ordenan las filas de la matriz tridimensional 'c' para cada combinación de las otras dos dimensiones. 
# Es decir, para cada par de índices en las dos primeras dimensiones, se ordenan los elementos a lo largo de la tercera dimensión.

Inciso 9.1
[1 2 3]
Inciso 9.2
[[[1.5 2.  1. ]
  [4.  5.  6. ]]

 [[3.  2.  3. ]
  [4.  5.  6. ]]]


## **Ejercicio 10)** Indexado y _slicing_ (rebanado) de arrays

**1)** Seleccione el segundo elemento de `a`.

**2)** Seleccione el elemento en la fila 1 y columna 2 de `b`.

Si `n` y `m` son enteros, luego `[n:m]` indica el rango de índices que van desde `n` hasta `m-1`.

**3)** Seleccione el rango `[0:2]` de elementos de `a`.

**4)** Seleccione los elementos de `b` en el rango `[0:2]` de filas y la columna `1`.

**5)** Seleccione todos los elementos de `b` que esten en el rango de filas `[0:1]` y el rango completo de columnas.

**6)** Uso de _elipsis_. Seleccione los elementos de `c` indexados por `[1,...]`. Es esto lo mismo que lo indexado por `[1,:,:]`?

Si `n`, `m` y `s` son enteros, luego `[n:m:s]` indica el rango de índices que van desde `n` hasta `m-1` saltando de a `s` elementos.

**7)** Utilice lo mencionado anteriormente para acceder a los elementos de `a` de forma invertida.

**8)** Seleccione los elementos de `a` que sean menores que dos.

**9)** Seleccione los elementos de `b` indicados por la lista de índices `[(1,0),(0,1),(1,2),(0,0)]` utilizando, correspondientemente, una lista de indices fila y una lista de índices columna.

**10)** Utilizando una lista de indices fila, seleccione las filas `1,0,1,0` de `b`, y luego, para cada selección anterior, utilice una lista de índices columna para seleccionar las columnas `0,1,2,0`.


In [26]:
# 10.1)
print("Inciso 10.1")
print(a[1])

# 10.2)
print("Inciso 10.2")
print(b[1][2])

# 10.3)
print("Inciso 10.3")
print(a[0:2])

# 10.4)
print("Inciso 10.4")
print(b[0:2, 1])

# 10.5)
print("Inciso 10.5")
print(b[0:2, :])

# 10.6)
print("Inciso 10.6")
print(c[1,...])
print(c[1,:,:])
# Si, es lo mismo.

# 10.7)
print("Inciso 10.7")
print(a[::-1])

# 10.8)
print("Inciso 10.8")
print(a[a < 2])

# 10.9)
print("Inciso 10.9")
row_indices = [1, 0, 1, 0]
col_indices = [0, 1, 2, 0]
print(b[row_indices, col_indices])

# 10.10)
print("Inciso 10.10")
row_indices = [1, 0, 1, 0]
col_indices = [0, 1, 2, 0]
print(b[row_indices, col_indices])


Inciso 10.1
2
Inciso 10.2
6.0
Inciso 10.3
[1 2]
Inciso 10.4
[2. 5.]
Inciso 10.5
[[1.5 2.  3. ]
 [4.  5.  6. ]]
Inciso 10.6
[[3. 2. 3.]
 [4. 5. 6.]]
[[3. 2. 3.]
 [4. 5. 6.]]
Inciso 10.7
[3 2 1]
Inciso 10.8
[1]
Inciso 10.9
[4.  2.  6.  1.5]
Inciso 10.10
[4.  2.  6.  1.5]


## **Ejercicio 11)** transposición

**1)** Use `np.transpose()` para calcular la traspuesta del array `b`, y asignarlo a una variable `i`.

**2)** Use `.T` para acceder a `i` de forma traspuesta. Es esta forma traspuesta igual a `b`?


In [ ]:
# 11.1)
print("Inciso 11.1")
i = np.transpose(b)
print(i)

# 11.2)
print("Inciso 11.2")
print(i.T)
print(b)

Inciso 11.1
[[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]
Inciso 11.2
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


## **Ejercicio 12)** Redimensionado

**1)** Use `.ravel()` para _achatar_ el array `b`.

**2)** Use `.reshape()` para redimensionar el array `g` de manera que adquiera dimensiones especificadas por la tupla `(3,-2)`.

**3)** Que indica aquí el signo negativo del segundo índice?


In [30]:
# 12.1)
print("Inciso 12.1")
print(b.ravel())

# 12.2)
print("Inciso 12.2")
g_reshaped = g.reshape(3, -2)
print(g_reshaped)

# 12.3)
# El signo negativo en el segundo índice de la tupla (-2) indica que NumPy
# debe calcular automáticamente el tamaño de esa dimensión en función del
# tamaño total del array y el tamaño de la otra dimensión especificada (3 en
# este caso). Esto es útil cuando no se conoce el tamaño exacto de una
# dimensión, pero se quiere que el array tenga una forma específica.

Inciso 12.1
[1.5 2.  3.  4.  5.  6. ]
Inciso 12.2
[[-0.5  0. ]
 [ 0.  -3. ]
 [-3.  -3. ]]


## **Ejercicio 13)** Agregando y quitando elementos

**1)** Use `np.resize()` para crear a partir del array `h` un nuevo array de tamaño y dimensiones diferentes indicadas por `(2,6)`.

**2)** Use `np.append()` para crear un nuevo array que agrege los elementos de `g` al final de los elementos de `h`. Notar que `h` y `g` tienen diferentes dimensiones. Cómo resuelve `numpy` esta cuestión?

**3)** Use `np.insert()` para crear una copia de `a` en donde se inserta el número `5` en la posición indexada por `1`.

**4)** Use `np.delete()` para eliminar los elementos de `a` indicados por la lista de índices `[1]`.


In [32]:
# 13.1)

print("Inciso 13.1")
h_resized = np.resize(h, (2, 6))
print(h_resized)

# 13.2)
print("Inciso 13.2")
hg_appended = np.append(h, g)
print(hg_appended)
# Numpy "achata" los arrays a una dimensión antes de concatenarlos.

# 13.3)
print("Inciso 13.3")
a_inserted = np.insert(a, 1, 5)
print(a_inserted)

# 13.4)
print("Inciso 13.4")
a_deleted = np.delete(a, [1])
print(a_deleted)


Inciso 13.1
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]]
Inciso 13.2
[ 1.   2.   3.  -0.5  0.   0.  -3.  -3.  -3. ]
Inciso 13.3
[1 5 2 3]
Inciso 13.4
[1 3]


## **Ejercicio 14)** Combinando arrays

**a)** Use `np.concatenate()` para concatenar los arrays `a` y `d`.

**b)** Use `np.vstack()` para apilar verticalmente los arrays `a` y `b`.

**c)** Use `np.hstack()` para apilar horizontalmente los arrays `e` y `f`.


In [33]:
# 14.1)
print("Inciso 14.1")
print(np.concatenate((a, d)))

# 14.2)
print("Inciso 14.2")
print(np.vstack((a, b)))

# 14.3)
print("Inciso 14.3")
print(np.hstack((e, f)))


Inciso 14.1
[ 1  2  3 10 15 20]
Inciso 14.2
[[1.  2.  3. ]
 [1.5 2.  3. ]
 [4.  5.  6. ]]
Inciso 14.3
[[7. 7. 1. 0.]
 [7. 7. 0. 1.]]


## **Ejercicio 15)** _Separando_ arrays

**a)** Use `np.hsplit()` para separar horizontalmente el array `a` en 3 partes.

**b)** Use `np.vsplit()` para separar verticalmente el array `c` en 2 partes.

**c)** Cree el array `z` dado por

    [[1, 2, 3, 4],
    [2, 0, 0, 2],
    [3, 1, 1, 0]]

y sepárelo en dos partes a lo largo del eje `1`.


In [34]:
# 15.1)
print("Inciso 15.1")
a_hsplit = np.hsplit(a, 3)
print(a_hsplit)

# 15.2)
print("Inciso 15.2")
c_vsplit = np.vsplit(c, 2)
print(c_vsplit)

# 15.3)
print("Inciso 15.3")
z = np.array([[1, 2, 3, 4],
              [2, 0, 0, 2],
              [3, 1, 1, 0]])
z_vsplit = np.hsplit(z, 2)
print(z_vsplit)


Inciso 15.1
[array([1]), array([2]), array([3])]
Inciso 15.2
[array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
        [4., 5., 6.]]])]
Inciso 15.3
[array([[1, 2],
       [2, 0],
       [3, 1]]), array([[3, 4],
       [0, 2],
       [1, 0]])]


## **Ejercicio 16)** Generando números aleatorios

**1)** Use `np.random.random()` para generar un número aleatorio de tipo float64 a partir de la distribución uniforme en $[0,1]$.

**2)** Use `np.random.random()` para crear un array de 10 números aleatorios de tipo float64 generados a partir de la distribución uniforme en $[0,1]$.

**3)** Use `np.random.random()` para crear un array dos dimensional de dimensiones `(3,4)` conteniendo números aleatorios de tipo float64 generados a partir de la distribución uniforme en $[0,1]$.

**4)** Use `np.random.randn()` para generar un número aleatorio de tipo float64 a partir de la distribución normal centrada en $\mu=0$ y de varianza $\sigma^2=1$.

**5)** Use `np.random.randn()` para generar un número aleatorio de tipo float64 a partir de la distribución normal centrada en $\mu=5$ y de varianza $\sigma^2=9$.

**6)** Use `np.random.randn()` para generar un array de dimensiones `(3,2,3)` conteniendo números aleatorios de tipo float64 generados a partir de la distribución normal centrada en $\mu=-1$ y de varianza $\sigma^2=2$.

**7)** Use `np.random.randint()` para generar un número aleatorio de tipo int64 a partir de la distribución uniforme en $\{0,1,2,3\}$.

**8)** Use `np.random.randint()` para generar un número aleatorio de tipo int64 a partir de la distribución uniforme en $\{10,11,12,13,14,15\}$.

**9)** Use `np.random.randint()` para generar un array de dimensiones `(3,2,3)` conteniendo números aleatorios de tipo int64 generados a partir de la distribución uniforme en $\{0,1\}$.

**10)** Use `np.random.choice()` para seleccionar uniformemente al azar un elemento de la lista `["perro","gato","loro","caballo","vaca"]`.

**11)** Use `np.random.choice()` para crear un array de dimensiones `(3,3)` con selecciones generadas uniformemente al azar de los elementos de la lista `["perro","gato","loro","caballo","vaca"]`.

**12)** Use `np.random.choice()` para crear un array de dimensiones `(3,3,3)` con selecciones generadas al azar de los elementos de la lista `["perro","gato","loro","caballo","vaca"]` de acuerdo a la correspondiente lista de probabilidades `[8/16,4/16,2/16,1/16,1/16]`.

**13)** Use `np.random.permutation()` generar una permutación, seleccionada uniformemente al azar una de las `n!` permutaciones que existen de un conjunto de `n` elementos, de una la lista de números entre `0` y `n-1` para `n=10` denominada `lista_n`.

**14)** Repita lo anterior usando `np.random.shuffle()` para aleatorizar la lista `lista_n` _in situ_.


In [36]:
# 16.1)

print("Inciso 16.1")
print(np.random.random())

# 16.2)
print("Inciso 16.2")
print(np.random.random(10))

# 16.3)
print("Inciso 16.3")
print(np.random.random((3,4)))

# 16.4)
print("Inciso 16.4")
print(np.random.randn())

# 16.5)
print("Inciso 16.5")
print(5 + 3 * np.random.randn())

# 16.6)
print("Inciso 16.6")
print(-1 + np.sqrt(2) * np.random.randn(3,2,3))

# 16.7)
print("Inciso 16.7")
print(np.random.randint(0, 4))




Inciso 16.1
0.33986157083814206
Inciso 16.2
[0.71425513 0.67864667 0.94205493 0.51871097 0.458701   0.02670849
 0.42731833 0.44460245 0.96552907 0.59392678]
Inciso 16.3
[[0.9865791  0.18415736 0.80622014 0.02291799]
 [0.65888669 0.59765863 0.89820723 0.02405361]
 [0.47393152 0.04137283 0.92912839 0.4114331 ]]
Inciso 16.4
-1.064573408298985
Inciso 16.5
5.162202282587878
Inciso 16.6
[[[-2.79858628  0.11929229 -1.63208091]
  [-1.27174114 -3.52618433  0.82795904]]

 [[-1.77701388  0.46270313  0.97722156]
  [-1.72428537 -2.4594696  -0.24060781]]

 [[-1.23541024  0.99424607 -2.27118977]
  [-1.36528845 -1.36003217 -2.10277928]]]
Inciso 16.7
0


In [40]:
# 16.8)
print("Inciso 16.8")
print(np.random.randint(10, 16, dtype=np.int64))

# 16.9)
print("Inciso 16.9")
array_3_2_3 = np.random.randint(0, 2, size=(3, 2, 3), dtype=np.int64)
print(array_3_2_3)

# 16.10)
print("Inciso 16.10")
animals = ["perro","gato","loro","caballo","vaca"]
random_animal = np.random.choice(animals)
print(random_animal)

# 16.11)
print("Inciso 16.11")
random_animals_array = np.random.choice(animals, size=(3, 3))
print(random_animals_array)

# 16.12)
print("Inciso 16.12")
probabilities = [8/16, 4/16, 2/16, 1/16, 1/16]
random_weighted_animals_array = np.random.choice(animals, size=(3, 3, 3), p=probabilities)
print(random_weighted_animals_array)


Inciso 16.8
12
Inciso 16.9
[[[1 0 1]
  [1 0 0]]

 [[0 1 1]
  [0 1 1]]

 [[1 0 1]
  [1 0 1]]]
Inciso 16.10
gato
Inciso 16.11
[['loro' 'perro' 'loro']
 ['gato' 'vaca' 'caballo']
 ['gato' 'perro' 'caballo']]
Inciso 16.12
[[['loro' 'perro' 'vaca']
  ['gato' 'gato' 'perro']
  ['gato' 'perro' 'gato']]

 [['perro' 'perro' 'gato']
  ['gato' 'gato' 'perro']
  ['perro' 'gato' 'perro']]

 [['gato' 'gato' 'gato']
  ['perro' 'loro' 'gato']
  ['perro' 'perro' 'perro']]]


In [41]:
# 16.13)
print("Inciso 16.13")
n = 10
lista_n = np.arange(n)
permuted_lista_n = np.random.permutation(lista_n)
print(permuted_lista_n)

# 16.14)
print("Inciso 16.14")
np.random.shuffle(lista_n)
print(lista_n)

Inciso 16.13
[9 6 8 7 4 0 2 3 5 1]
Inciso 16.14
[6 9 5 0 2 3 4 7 8 1]
